name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install SDL2
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev

      - name: Download catch
        run:
          wget https://github.com/catchorg/Catch2/releases/download/v3.8.1/catch_amalgamated.hpp ./tests &&
          wget https://github.com/catchorg/Catch2/releases/download/v3.8.1/catch_amalgamated.cpp ./tests

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.25.0"

      - name: Configure CMake
        run: cmake -B build -S . -DBUILD_TESTS=ON

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
